### ISSUE TITLE
Creating self-enclosing HTMLElement

### ISSUE THREAD

**Issue by igrekde** [nolanw/HTMLReader#15]
Hi!
I'm trying to create a self-enclosing HTMLElement - the <link href="composition.css" rel="stylesheet" type="text/css"/> one. Is there any way to do it?

**Comment by nolanw** [comment]
Nope. A total oversight on my part. Let me get into it!

**Comment by nolanw** [comment]
Actually, I think what you're looking for already works. The elements that are always self-enclosing (aka. [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements)) work just fine:
```swift
let img = HTMLElement(tagName: "img", attributes: {"src": "updog.png"})
println(img.serializedFragment)
// prints: <img src="updog.png">
```
Some elements have an [optional end tag](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission) (like `<li>` or `<p>`), but there isn't any advantage I can see to dealing with all the special cases, so HTMLReader always includes end tags:
```swift
let li = HTMLElement(tagName: "li", attributes: nil)
println(li.serializedFragment)
// prints: <li></li>
```

And if you're worried about the trailing `/` just before the `>`, don't be: [it's optional](https://html.spec.whatwg.org/multipage/syntax.html#start-tags).

Does all of that makes sense?

**Comment by igrekde** [comment]
@nolanw thanks a lot for pointing me at html specs :) I was sure that **/** is obligatory.

And thanks for a great lib!

**Comment by nolanw** [comment]
You're most welcome!
