### ISSUE TITLE
Selector with or

### ISSUE THREAD

**Issue by joscha-alisch** [nolanw/HTMLReader#17]
Hey,

i'm trying to get some elements via the selector (@".class1, .class2"), to get elements that either have class1 or class2. But it doesn't work. I get the following Parsing Error:

    Attempted to use selector with error: Error Domain=HTMLSelectorErrorDomain Code=1 "Expected a 
    combinator here" UserInfo=0x6100000f2f80 {NSLocalizedFailureReason=Error near character 7:
    Expected a combinator here

	.class1, .class2
	^       , HTMLSelectorInputString=.class1, .class2, HTMLSelectorLocation=7, NSLocalizedDescription=Expected a combinator here}

Is it simply not supported?

best regards,
Joscha

**Comment by nolanw** [comment]
Hello! Unfortunately, that is not currently supported.

For now, you're stuck with getting two arrays from calling `-nodesMatchingSelector:` and merging them together (watch out for duplicates!).

It is the next thing I want to implement, however.

**Comment by joscha-alisch** [comment]
Yeah thats what i did as a quick fix :) Thanks for the quick response, looking forward to the implementation, but take your time of course :)

**Comment by luttmerk** [comment]
Fix this for me please. :)

**Comment by nolanw** [comment]
@joscha-alisch @luttmerk I just released HTMLReader 0.9 which adds support for selector groups. Try it out and let me know how it goes!
