### ISSUE TITLE
Handle tagName with a : in it

### ISSUE THREAD

**Issue by tberman** [nolanw/HTMLReader#19]
I am getting back some html that has some namespaced elements in it, like:

`<some-ns:some-tag />` and I am unable to build a selector that targets it, as it chokes on the `:`.

**Comment by nolanw** [comment]
Fair enough – looks like we need to implement some selector escaping! I'll stick it on the todo list and keep this issue updated.

Unfortunately the best I can do for a workaround right now is to use a selector to get a nearby element (maybe the parent element) and then climb around the tree until you find the right elements. `-[HTMLElement tagName]` should handle the colon just fine.

**Comment by nolanw** [comment]
Amusingly enough, part of the impetus for starting HTMLReader was encountering elements that looked like `<size:8>` and having libxml2's HTML parser choke on it.

**Comment by nolanw** [comment]
@tberman I just released HTMLReader 0.7.1 which includes support for escaping characters in selectors. For example, you can now use the selector `some-ns\:some-tag` to match your example element. Give it a try and let me know how it goes!

**Comment by tberman** [comment]
Working great, thanks!
