### ISSUE TITLE
Access element via item prop

### ISSUE THREAD

**Issue by jacobhull** [nolanw/HTMLReader#21]
Is it possible to access an HTML element based on it's itemprop that is used by schema.org? Thanks!

**Comment by nolanw** [comment]
Hello! Did you mean schema.org?

Anyway, HTMLReader doesn't know about itemprop or related attributes, so it doesn't go out of its way to help you use them.

I'm not too familiar with microdata but I think you can get the job done with the usual selectors and maybe a bit of processing thereafter. Remember that you can use `~=` in a selector to match whitespace-delimited values in an attribute. For example,
```css
foo[itemprop ~= 'up']
```
will match this element:
```html
<foo itemprop="whats up dog" />
```

If you get stuck, I'd be happy to look at some markup and suggest ways to extract the elements you need.

**Comment by jacobhull** [comment]
Yep meant schema.org. Thanks for the help, thats what I needed to get it working!

**Comment by nolanw** [comment]
Glad to hear it!
