### ISSUE TITLE
Whitespace issue

### ISSUE THREAD

**Issue by henneonrails** [nolanw/HTMLReader#22]
in your example code you do `stringByTrimmingCharactersInSet`. For my parsed string it makes no difference if I trim or not. The string always looks the same: completely without any whitespace characters. 

But I would like the opposite. I would like a parsed text with newline characters. Is it possible to get this text?

Here is the text http://www.dwd.de/bvbw/appmanager/bvbw/dwdwwwDesktop?_nfpb=true&_state=maximized&_windowLabel=T43402027281174298183241&T43402027281174298183241gsbDocumentPath=Navigation%2FSchifffahrt%2FSeewetter%2FNavtex__Empfang__518__Emden__node.html%3F__nnn%3Dtrue&_pageLabel=_dwdwww_spezielle_nutzer_schiffffahrt_seewetter&switchLang=de

and the node I look at is `.blockBodyPre` .

In webinspector I can see that the text is shown like parsed with HTMLReader, but in Safari it shows with newlines.

**Comment by henneonrails** [comment]
`.innerHTML` will do the job

**Comment by nolanw** [comment]
@henneonrails When I try to scrape that page and look at the `.blockBodyPre`'s `textContent`, I see newlines all over the place, just like the page itself. How are you inspecting the parsed text?

Not coincidentally, I've added a playground to the project to aid in this kind of verification. If you end up trying it out and can show me what you mean with some playground code, I'd be more than happy to take a look.

But it seems like you have found a workable solution, so I understand if you have no desire to spend more time on it!
