### ISSUE TITLE
<HTMLReader/HTMLReader.h> file not found

### ISSUE THREAD

**Issue by kiraniphone** [nolanw/HTMLReader#23]
How can i instal the framework?

**Comment by irbaaz** [comment]
Its easy create a Folder HTMLReader and copy all the files of code folder in it .
Than open xcode file->Add File to "Project_name".
you are done than

**Comment by nolanw** [comment]
@kiraniphone The easiest ways are to use CocoaPods or Carthage. If you copy the files over manually like @irbaaz suggests, you may have to add the folder containing HTMLReader to your project's build settings under "Header Search Paths". Does that make sense?

**Comment by nolanw** [comment]
Hopefully that made sense! Gonna close this as it's been a month, but please do reopen or create a new issue as needed.
