### ISSUE TITLE
Mach-o error

### ISSUE THREAD

**Issue by irbaaz** [nolanw/HTMLReader#24]
Don't know how to sort it .

I have imported Foundation library already.

When using HTMLDocument xcode giving error :

 ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by irbaaz** [comment]
Found the issue Files were not compiling. Now sort out

**Comment by nolanw** [comment]
@irbaaz what was preventing some files from compiling? I'd like to make the installation instructions as clear as possible.

**Comment by irbaaz** [comment]
Hi Thank you for your response .

I have done the following First I have add the Foundation framework files than add the files from file menu not by drag and drop.

**Comment by nolanw** [comment]
@irbaaz sounds good, thanks!

**Comment by irbaaz** [comment]
I am facing one more issue ex: my HTML is <li <td class='nfo' <a HELLO1 /a>/td> <td class='ttl' <a HELLO2/a>/td>

Now how I can pick particular class data  .

**Comment by nolanw** [comment]
Just like in CSS. `[document nodesMatchingSelector:@".updog"]` selects all nodes with the class `updog`.

(If you put your HTML within triple-backticks it'll show up nicely in the issue. See the "code" section at https://guides.github.com/features/mastering-markdown/)

**Comment by irbaaz** [comment]
Thanks alot it worked .

I have switched from hpple library to yours because in xcode 7 it were causing issues.

I am playing around with it from past 2 days.

Now I have learned enough to integrate this in my old code .

Thanks for developing this simple library .

**Comment by nolanw** [comment]
You are most welcome!
