### ISSUE TITLE
[closed]Analyse src content in html str

### ISSUE THREAD

**Issue by 0x0007de** [nolanw/HTMLReader#25]
Hi,
     I want to analyse "some.jpg"  in the html str blow.
     What should I do? Thank you.

    <div class="box-border" style="height:700px;">
    <ul id="Cont01">
    <li style="display:block" id="projectContainer"><div class="spacing"></div><center><img src="some.jpg"></center><hr></li>
    </ul>
    </div>

**Comment by nolanw** [comment]
Something like this?

```objc
NSString *someString = /* your document */;
HTMLDocument *document = [HTMLDocument documentWithString:someString];
HTMLElement *img = [document firstNodeMatchingSelector:@"#Cont01 img"];
NSString *src = img[@"src"];
NSLog(@"%@", src"); // should print "some.jpg"
```

**Comment by 0x0007de** [comment]
Thank you very much!!

I think it will work too.

    HTMLElement *element = [document firstNodeMatchingSelector:@"#projectContainer center img"];
    NSLog(@"textContent is %@",[element objectForKeyedSubscript:@"src"] );
