### ISSUE TITLE
iOS 9 / Xcode 7 compatibility issue

### ISSUE THREAD

**Issue by irbaaz** [nolanw/HTMLReader#26]
HTMLTreeEnumerator.m:20:17: Method override for the designated initializer of the superclass '-init' not found

HTMLPreprocessedInputStream.m:8:17: Method override for the designated initializer of the superclass '-init' not found

HTMLParser.m:50:17: Method override for the designated initializer of the superclass '-init' not found

HTMLSelector.m:790:17: Method override for the designated initializer of the superclass '-init' not found

HTMLTokenizer.m:2596:17: Method override for the designated initializer of the superclass '-init' not found

This are the warnings I am seeing in Xcode 7

**Comment by nolanw** [comment]
@irbaaz How's the master branch looking now? If it looks ok, I'll wrap everything up into a new release.

**Comment by irbaaz** [comment]
Everything is working fine without any issue , only showing this as warning.

**Comment by nolanw** [comment]
@irbaaz you're still seeing a warning on master branch?

**Comment by irbaaz** [comment]
'HTMLReader/HTMLNamespace.h' file not found

Even it has this file in the folder still giving this error . I have tried to replace this file from old HTMLReader folder but still same issue.

**Comment by irbaaz** [comment]
Now it is showing file missing HTMLNamespace.h 

I am trying to put code of specific files one by one and trying to analyse .

**Comment by irbaaz** [comment]
Now the warning has been limited to two files : 
Method override for the designated initializer of the superclass '-init' not found
Method override for the designated initializer of the superclass '-init' not found

One has no warning and on using that same modified libraries to other project giving two warnings as stated above :

https://drive.google.com/file/d/0BwM-1nlIgG_ddGV0QTdYbERDQVE/view?usp=sharing

https://drive.google.com/file/d/0BwM-1nlIgG_dQlllbmdpQmlEcmM/view?usp=sharing

**Comment by irbaaz** [comment]
Issue is Looking fixed now :

 Importing the folder containing file with folder name HTMLReader fixes the issue .

https://drive.google.com/file/d/0BwM-1nlIgG_dQlllbmdpQmlEcmM/view?usp=sharing

I think this issue can be closed now.

**Comment by nolanw** [comment]
@irbaaz While we're talking Xcode 7, have you looked at Objective-C generics at all? I've just updated master with generics, and since you seem to be my Xcode 7 tester I thought you might be interested. If not, that's ok!

**Comment by irbaaz** [comment]
I am a beginner , not familiar with Objective-C generics will study about them.

I can not say issue is solved .

Initially it is working fine but when using the functions HTMLDocument it is giving error Mach-o Linker

**Comment by irbaaz** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_HTMLDocument", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nolanw** [comment]
@irbaaz you are using HTMLReader by copying the files into your project, correct? If so, can you make sure that the `HTMLDocument.m` file has been added to the target you're trying to build?

**Comment by irbaaz** [comment]
Yes I am 100% sure it is there just checked it again.

**Comment by irbaaz** [comment]
Ok it was a compiling issue now it is sorted but two warning pop-up than:

HTMLTokenizer.m
Method override for the designated initializer of the superclass '-init' not found
HTMLParser.m
Method override for the designated initializer of the superclass '-init' not found

**Comment by irbaaz** [comment]
Hi ,
I have gone through new update objective-c generics and it is causing the same issue .

**Comment by nolanw** [comment]
I haven't forgotten about you! I'll take a look in the next few days.

**Comment by irbaaz** [comment]
Thanks for remembering me .
My app is ready :)

**Comment by nolanw** [comment]
Everything's warning-free for me with Xcode 7 beta 2, so I've just wrapped up and pushed HTMLReader 0.8. Thanks for the push to get it updated!

**Comment by irbaaz** [comment]
Finally all things are looking great no warning , everything is set .

I have to remove <HTMLReader/ from every file .

I am uploading the folder and sharing the link with you . I would strongly suggest you to upload that separately that will work only with just adding the files in there existing project.

https://drive.google.com/file/d/0BwM-1nlIgG_deWtLT2dPaXFqS28/view?usp=sharing

**Comment by nolanw** [comment]
@irbaaz instead of removing `<HTMLReader/>` from everything, you could do one of:

* Add the folder with HTMLReader to your "Header Search Paths" build setting. e.g. add "${PROJECT_DIR}/External/HTMLReader" and tick the "Recursive" box.
* Instead of adding all the files to your target, drag HTMLReader.xcodeproj into your app project, then add HTMLReader.framework to your app's "Embedded Binaries" in the General tab.

**Comment by irbaaz** [comment]
Thanks for your support and help....

**Comment by nolanw** [comment]
Alright I'ma close this issue as I think Xcode 7 compatibility is addressed, but please by all means c'mon back if you need anything else!

**Comment by irbaaz** [comment]
Yes sure .
Thanks for everything.
