### ISSUE TITLE
Possible to access video id?

### ISSUE THREAD

**Issue by wraithseeker** [nolanw/HTMLReader#28]
I am pretty unfamiliar with HTML scraping but as far as the documentation goes, it covers mostly about imgs and text.

Does HTMLReader have the ability to scrape video urls such as this one?

     <video id="my_video_1_html5_api" class="vjs-tech" preload="auto" src="https://redirector.googlevideo.com/videoplayback?requiressl=yes&amp;id=45d2fdf73f5ea442&amp;itag=22&amp;source=picasa&amp;cmo=secure_transport%3Dyes&amp;ip=0.0.0.0&amp;ipbits=0&amp;expire=1438962730&amp;sparams=requiressl,id,itag,source,ip,ipbits,expire&amp;signature=A1870313E674D7D0FAAA420CB49BAC57C744A158.45144C1E44617AE5405CE7A27517A4B84DDAE50C&amp;key=lh1"></video>

**Comment by nolanw** [comment]
Shouldn't be a problem! You'd just do something like

```objc
HTMLDocument *document = /* load this somehow */;
HTMLElement *video = [document firstNodeMatchingSelector:@"#my_video_1_html5_api"];
NSString *src = video[@"src"];
// If the string doesn't parse as a URL, this will be nil.
NSURL *URL = [NSURL URLWithString:src];
```

Make sense?

**Comment by wraithseeker** [comment]
HTMLElement *video = [document firstNodeMatchingSelector:@"#my_video_1_html5_api"];

This line seems to be returning nil for me

**Comment by nolanw** [comment]
I wonder if there's some JavaScript that runs in the browser, changing the HTML that's initially served up. I tried:
```swift
let video = home.firstNodeMatchingSelector("video")
video?.objectForKeyedSubscript("id") // prints "my_video_1"
video?.objectForKeyedSubscript("src") // nil
```
I suspect this makes your problem a bit tricker to solve, as HTMLReader won't execute any scripts for you. Maybe you can poke around on the page a bit and figure out how it's determining and inserting the video's `src`?

**Comment by nolanw** [comment]
@wraithseeker did you ever solve this?

**Comment by wraithseeker** [comment]
The last time I did this, I realized the website's video url is loaded through an ajax call which is probably the issue. I didn't solve this.

**Comment by nolanw** [comment]
Alright, I'ma close this because it doesn't seem to be a problem with HTMLReader.
