### ISSUE TITLE
innerHTML in the xhtml

### ISSUE THREAD

**Issue by smallwood69** [nolanw/HTMLReader#33]
&lt;img src = '...' /&gt; is convert to &lt;img src='...'&gt;

so, xhtml  contents display error.

xhtml contents have to  tag close.

how can i fix it.

**Comment by nolanw** [comment]
Unfortunately there's no way to do XHTML output with HTMLReader.

I don't plan on adding support myself, but if anyone else is interested in doing the work then I would happily help and merge it in!
