### ISSUE TITLE
Parse attributed HTML?

### ISSUE THREAD

**Issue by priyansh1990** [nolanw/HTMLReader#36]
How to parse attributes in HTML element like name and value?
![screen shot 2015-08-24 at 11 59 24 am](https://cloud.githubusercontent.com/assets/6958908/9434111/bb4b295a-4a58-11e5-8239-b763d238ab6a.png)

**Comment by nolanw** [comment]
Suppose you had that HTML in a string variable called `markup`. Then:
```objc
HTMLDocument *document = [HTMLDocument documentWithString:markup];
NSArray *inputs = [document nodesMatchingSelector:@"input"];
for (HTMLElement *input in inputs) {
    NSLog(@"name: %@; value: %@", input.attributes[@"name"], input.attributes[@"value"]);
}
```

You might need to get fancier with the selector used to find the input elements in the first place, as I'm guessing your document won't be quite so straightforward as the sample you included.

**Comment by priyansh1990** [comment]
Thank You for your help and prompt reply.

**Comment by priyansh1990** [comment]
Thanks a lot Nolan. This helped a lot

**Comment by nolanw** [comment]
Glad to hear it!
