### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by jawb** [nolanw/HTMLReader#44]
Hi,

I added HTMLReader through pod as instructed, but the project isn't compiling, I get the following message:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_HTMLDocument", referenced from:
      objc-class-ref in FetchData.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea ?

**Comment by nolanw** [comment]
Did you get it figured out?

**Comment by ssk7833** [comment]
Have the same issue, just need to add HTMLReader source code into TargetSettings -> Build Phases -> Compile Sources and rebuild.

http://stackoverflow.com/a/9438843/4968420
