### ISSUE TITLE
Build failed when in testing of my OS X App.

### ISSUE THREAD

**Issue by mrahmiao** [nolanw/HTMLReader#45]
Xcode 7.1 and OS X 10.11.1, OS X app.

I used Carthage to install HTMLReader, when build for my test target, error occurred: 

> ld: framework not found HTMLReader for architecture x86_64

This error only occurs in the test bundle.

If I install HTMLReader through Git Submodule, everything is OK.

**Comment by nolanw** [comment]
Hello! I just made a new OS X project using Xcode 7.1, added HTMLReader to a Cartfile, ran `carthage update`, then [followed these directions](https://github.com/carthage/carthage#adding-frameworks-to-unit-tests-or-a-framework). I'm not seeing any errors.

Do you get the same error in a new Xcode project?

**Comment by nolanw** [comment]
I should add that I'm not seeing any errors linking either my app or my unit test target, both of which import HTMLReader and make a new HTMLDocument.

**Comment by mrahmiao** [comment]
Fixed.

**Comment by nolanw** [comment]
Great! Was there anything in particular you needed to do?

**Comment by mrahmiao** [comment]
Haven't done anything special.

**Comment by passol1988** [comment]
same issue happened

**Comment by nolanw** [comment]
@passol1988 can you share any reproduction steps? I had a hard time reproducing the error before.
