### ISSUE TITLE
String to HTML is not complete

### ISSUE THREAD

**Issue by Jacenty10** [nolanw/HTMLReader#46]
I can't get right html string when plan source text contains newline character.

Result HTML contains " \ n ", not "< br >" or "< p >" tag.

**Comment by nolanw** [comment]
Hello! Do you have an example of what your plain source text looks like, and what you'd like the resulting HTML to look like?

HTMLReader will not automatically turn `\n` into `<br>` for you. It can assist you in doing so, though I question how much help it will be. But I'm happy to help if you can tell me a bit more about what you'd like to do.

**Comment by Ying1986** [comment]
@nolanw 

I have same issue.
----
    NSString * q = @"<br><br>abc<p>1</p> qq";
    
    HTMLDocument* document = [HTMLDocument documentWithString: q];

    NSString*c2 = document.textContent;

---
  c2 = "abc1 qq",
and <div> tags are processed as one line.

Please help me.

Thank you.

**Comment by nolanw** [comment]
@Ying1986 I think you'll have to do a bit more work than simply taking the `textContent` of the document. `document.textContent` grabs all of the text nodes in the document. `<br>` isn't a text node; it's an element. If you'd like to turn `<br>` into a line break, you can, but it's a bit obtuse (code untested):

```objc
HTMLDocument *doc = [HTMLDocument documentWithString:@"<br><br>abc<p>1</p> qq"];
NSLog(@"%@", doc.textContent); // no newlines

for (HTMLElement *br in [doc nodesMatchingSelector:@"br"]) {
    HTMLNode *parent = br.parentNode
    NSMutableOrderedSet *children = parent.mutableChildren;
    NSUInteger i = [children indexOfObject:br];
    HTMLTextNode *text = [[HTMLTextNode alloc] initWithData:@"\n"];
    [children replaceObjectAtIndex:i withObject:text];
}

NSLog(@"%@", doc.textContent); // newlines!

```

**Comment by Ying1986** [comment]
@nolanw 

Thanks for your help.

Your library is useful, but it has some issues like newline.

if < br > is ok, then how about < p > tag?

< div >  my line1 < /div > < div >  my line2 < /div >   ????

In fact, I have only one useful library for this.
It is NSAttributedString, but it generate some classes and styles.

Can you make your library like as NSAttributedString, but not classes and styles?

**Comment by nolanw** [comment]
@Ying1986 The same basic idea should work for `<p>` tags, though you'd have to be careful not to delete its text contents.

HTMLReader would probably be quite helpful to someone who wants to turn HTML into an NSAttributedString, but it's not what I have in mind for HTMLReader itself. It would not be too difficult to make something that, for example, consumes an HTMLTreeEnumerator and builds up an NSMutableAttributedString as it goes.

If you go down that road, and you're interested in sharing afterwards, I'd love to see what you end up with!

**Comment by Ying1986** [comment]
@nolanw 

Following is some of my code using HTMLReader

<p>- (NSString*) my_planstringFromHTML<br />
{<br />
&nbsp; &nbsp; if (self.length == 0)<br />
&nbsp; &nbsp; &nbsp; &nbsp; return self;<br />
&nbsp; &nbsp;&nbsp;<br />
// &nbsp; &nbsp;HTMLDocument* document = [HTMLDocument documentWithString: self];<br />
// &nbsp; &nbsp;return document.textContent;<br />
&nbsp; &nbsp;&nbsp;<br />
&nbsp; &nbsp; NSDictionary* htmlInfo = @{NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType, NSCharacterEncodingDocumentAttribute: [NSNumber numberWithInt:NSUTF8StringEncoding]};<br />
&nbsp; &nbsp; NSData* htmlData = [self dataUsingEncoding:NSUTF8StringEncoding];<br />
&nbsp; &nbsp;&nbsp;<br />
&nbsp; &nbsp; NSAttributedString* attr = [[NSAttributedString alloc] initWithData: htmlData<br />
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; options: htmlInfo<br />
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;documentAttributes:nil error: nil];</p>

<p>&nbsp; &nbsp; return attr.string;<br />
}</p>

I can't get correct string which contains newlines tag. It missed line information.
So I have used NSAttributesString.

Let me see your opinion about that.

Thank you.

**Comment by nolanw** [comment]
@Ying1986 Right, you'd need to do some extra processing like I suggested earlier in order to transform elements into the spacing you want.

**Comment by nolanw** [comment]
As eager as I am to hear the end of this story, I think any extra functionality described here doesn't belong in HTMLReader proper.
