### ISSUE TITLE
HTMLElement's `objectForKeyedSubscript:` is not imported into Swift as `subscript`

### ISSUE THREAD

**Issue by nolanw** [nolanw/HTMLReader#59]
If you try e.g.
```swift
let e: HTMLElement = …
let value = e["key"]
```
you get
> Type 'HTMLElement' has no subscript members

But if you do
```swift
extension HTMLElement {
    subscript(attributeName: String) -> String? {
        return objectForKeyedSubscript(attributeName) as? String
    }
}
```
you get
> Subscript getter with Objective-C selector 'objectForKeyedSubscript:' conflicts with method 'objectForKeyedSubscript' with the same Objective-C selector

---

This works:
```swift
extension HTMLElement {
    @nonobjc subscript(attributeName: String) -> String? {
        return objectForKeyedSubscript(attributeName) as? String
    }
}
```
but I think it shouldn't be necessary? It seems like Swift usually maps `-objectForKeyedSubscript:` to `subscript`, so why is it failing here?

**Comment by nolanw** [comment]
Still seems to be broken.

**Comment by herau** [comment]
@nolanw 
I use the cocoapods version (2.0.3) but i don't have your fix f021921.
Do you know when a new release will be available please ?

Thanks

**Comment by nolanw** [comment]
@herau that commit should absolutely be there in CocoaPods version 2.0.3. After you `pod install` do the source files in `Pods/HTMLReader` have the correctly-spelled `#if !__has_feature(objc_generics)` line? If they do, can you try clearing your `DerivedData` folder and rebuilding?

**Comment by herau** [comment]
i don't find any `#if !__has_feature(objc_generics)` stuff in the `Pods/HTMLReader`.

if you check the HTMLElement.m file in the 2.0.3, it doesn't contains your code from f021921.

https://github.com/nolanw/HTMLReader/blob/v2.0.3/Sources/HTMLElement.m#L40

**Comment by nolanw** [comment]
@herau It's the `.h` that affects how Swift imports the type and the change is present there: https://github.com/nolanw/HTMLReader/blob/v2.0.3/Sources/include/HTMLElement.h#L39

The `.m` doesn't affect anything but the mismatch is confusing so I'll fix that up. I don't think it'll solve your problem though.

Are you getting a Swift compile error when you try to subscript an HTMLElement instance?

**Comment by herau** [comment]
yes swift compile error `Error:(328, 54) 'objectForKeyedSubscript' is unavailable: use subscripting`

with this kind of code 

```swift
            var receiptInput: HTMLElement? = nil
            for input in inputs {
                receiptInput = input as! HTMLElement
                var nameAttr: String = receiptInput!.objectForKeyedSubscript("name")!
                if nameAttr.compare(jobReceiptName!) == .orderedSame {
                    break
                }
            }
```

**Comment by nolanw** [comment]
@herau Oh, I see. The Swift importer tries to import Objective-C subscripts as Swift subscripts, and I'd somehow managed to do it wrong and expose `objectForKeyedSubscript` directly. Can you try changing the code you posted to:
```swift
            var receiptInput: HTMLElement? = nil
            for input in inputs {
                receiptInput = input as! HTMLElement
                var nameAttr: String = receiptInput["name"]! // I changed this line
                if nameAttr.compare(jobReceiptName!) == .orderedSame {
                    break
                }
            }
```
and see how that works?

**Comment by herau** [comment]
it's works thanks a lot @nolanw

**Comment by nolanw** [comment]
@herau Happy to hear it! Hope the project turns out well.
