### ISSUE TITLE
Parsed Document back to String

### ISSUE THREAD

**Issue by rushk2112** [nolanw/HTMLReader#64]
I've been looking through the source and have been trying to find a way to get the parsed document back as a string. I am trying to use the library to parse apart an HTML document to then search for elements and remove and/or replace some attributes so that they will render within a WKWebview.

I have the the changes working (examining the .attributes) but can not find a way to get the main document to create a string I can then feed into the WebView.

Any insight would be appreciated!

Thanks,
  Rob

**Comment by nolanw** [comment]
Hello! I think `yourDocument.serializedFragment` might suit your needs. Let me know if it does, and I'll make it more obvious for the next person!

**Comment by rushk2112** [comment]
Wonderful! A thousand thanks that did the trick. I finally found that in the code and had even tried document.innerHTML  with no success. Since I'm using Swift I even tried the .description and .toString.

Your quick response has let me move forward again...  I knew it had to be me :^)
