### ISSUE TITLE
Importing files directly on project doesn't work anymore

### ISSUE THREAD

**Issue by leolobato** [nolanw/HTMLReader#65]
From the README, one of the options of installation is:

> Copy the files in the Code folder into your project.

I've added HTMLReader to a project back in version 0.7 using git submodule and imported the files directly into it, but now when I pulled the latest revision, the app won't build anymore because of the `#import <HTMLReader/*>` imports.

**Comment by nolanw** [comment]
Oh, good point! My bad. The static library target is probably broken too for the same reason.

I'll need to think about whether there's a better way to handle this, and update the README. In the meantime, I think we can get you up and running with one more step: adding the HTMLReader folder to your app target's "Header search paths" build setting.

If your folder hierarchy for your project looks something like:
* App.xcodeproj
* Source
  * bunch of files
* Vendor
  * HTMLReader
    * files copied over from this repo

then you'll want to add a header search path that looks like `Vendor/`

Let me know if any of this is unclear or if you get stuck. I realize it's pretty finicky.

**Comment by nolanw** [comment]
@leolobato I think I may have fixed things in version 0.9.6. Can you give that a try at your convenience? Let me know if it works!

**Comment by leolobato** [comment]
@nolanw Pulled in 0.9.6 on my project and it worked! Thanks for the fix!

**Comment by nolanw** [comment]
Gonna close this for now, but I'm guessing I just broke things again for you @leolobato by rearranging the folder structure. Please reopen if you get stuck!
