### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by mgolovko** [nolanw/HTMLReader#66]
Hi!

My HTML contains custom not closed tag, as a `<tag>` or `<tag/>`. HTMLReader expecting `<tag></tag>`, so my document does not good for me.
I can customize parse process, to add support for my tags?

Thanks!

**Comment by nolanw** [comment]
Hello! There's no convenient point to customize parsing like that in the public API. However, if you're willing to maintain a modified version of HTMLReader, I believe you can add your tag name to [this list in HTMLParser.m](https://github.com/nolanw/HTMLReader/blob/1bcbfbd35bb6cfd30476ce80bd8b943aabb8a0d6/Code/HTMLParser.m#L845) and to [this other list in HTMLParser.m](https://github.com/nolanw/HTMLReader/blob/1bcbfbd35bb6cfd30476ce80bd8b943aabb8a0d6/Code/HTMLParser.m#L1222) and you might get the behaviour you're looking for. Does that help?

**Comment by mgolovko** [comment]
Yes! That solve my problem.
Thanks for the quick response!

**Comment by nolanw** [comment]
You're very welcome! I'll close this issue for now, but please feel free to (re)open as needed.
