### ISSUE TITLE
parse html..

### ISSUE THREAD

**Issue by ilyi1116** [nolanw/HTMLReader#68]
Hi

i want to parse an one html. here is an html code :
```
<p>可愛的兔兔應該是繼汪星人和喵星人之外比較常見的家庭寵物，而在日本就有一隻垂耳兔PuiPui不只本身擁有超萌的高顏值，她的主人也很用心地幫PuiPui準備專屬服裝，並且在Instagram上分享牠的變裝日記，讓PuiPui成為超多粉絲追蹤的人氣時尚潮兔，快一起來認識PuiPui吧！</p>

<figure>
  <img src="http://images.900.tw/upload_file/33/content/dc38a115-5732-b707-34d2-83513508a273.jpg" />
  <figcaption>哥什麼造型都能消化！超卡哇伊又高顏值的萌兔PuiPui穿搭日記圖集...第12張簡直是撩妹高手呀！</figcaption>
</figure>


<p>▼穿上可愛的學生制服、萌兔PuiPui要在櫻花的目送下上學去啦！</p>
<a href="http://www.styletc.com/wp-content/uploads/2016/05/110.jpg">
<figure>
  <img src="http://www.styletc.com/wp-content/uploads/2016/05/110.jpg" />
  <figcaption>哥什麼造型都能消化！超卡哇伊又高顏值的萌兔PuiPui穿搭日記圖集...第12張簡直是撩妹高手呀！</figcaption>
</figure>
</a>

<p>▼到了秋天就換上福爾摩斯裝來襯托深沉的秋意！</p>

<figure>
  <img src="http://www.styletc.com/wp-content/uploads/2016/05/28.jpg" />
  <figcaption>哥什麼造型都能消化！超卡哇伊又高顏值的萌兔PuiPui穿搭日記圖集...第12張簡直是撩妹高手呀！</figcaption>
</figure>
```

i want to parse an 'p', 'figure.img', 'figure.figcaption', 'a' and by default sort.....
i don't know how to user HTMLDocument to parse this...

Could you help me? 
Thanks

**Comment by nolanw** [comment]
Hello! I think I can help you. Let's find out!

First, how are you receiving the HTML that you want to parse? If it's downloaded data, you can make an HTMLDocument like so:
```objc
// Don't do this on your main thread! Bad user experience.
NSData *data = [NSData dataWithContentsOfURL:[NSURL URLWithString:@"http://…"]];
HTMLDocument *doc = [HTMLDocument documentWithData:data contentTypeHeader:nil];
```
If you've got the HTML as a string already, you can do:
```objc
NSString *html = [NSString stringWithContentsOfFile:@"…"];
HTMLDocument *doc = [HTMLDocument documentWithString:html];
```

Either way, once you've created your HTMLDocument, you can find nodes using CSS selectors, like so:

```objc
NSArray *allTheParagraphs = [doc nodesMatchingSelector:@"p"];

for (HTMLElement *figure in [doc nodesMatchingSelector:@"figure"]) {
  HTMLElement *img = [figure firstNodeMatchingSelector:@"img"];
  HTMLElement *caption = [figure firstNodeMatchingSelector:@"figcaption"];
}
```

Does any of that help? Give it a try and if you get stuck, by all means please c'mon back!

**Comment by ilyi1116** [comment]
@nolanw 

very thank you 
it is help me a lot~~

here is my code :

 ```
            var parser     = HTMLParser(html: str!, error: &err)
            let objcString:String = str as! String // results in error

            let document = HTMLDocument(string: objcString)
            
            let allTheParagraphs = document.nodesMatchingSelector("p")
            
            debugPrint("allTheParagraphs : \(allTheParagraphs)")
            for figure in document.nodesMatchingSelector("figure") {
                
                debugPrint("img", figure.firstNodeMatchingSelector("img"))
                debugPrint("caption", figure.firstNodeMatchingSelector("figcaption"))
            }

```

**Comment by ilyi1116** [comment]
i have another question... if my html is dynamic. like this :
![2016-05-17 10 13 43](https://cloud.githubusercontent.com/assets/517366/15309287/1946189e-1c18-11e6-93f2-1bd021cbff28.png)

not the same as 'p' tag was before 'figure'... how to parse it and default sort...@@

**Comment by nolanw** [comment]
I'm not totally sure what you're looking for, but if you'd like the `p` tags that come immediately before a `figure` tag, you might do something like:
```swift
for figure in document.nodesMatchingSelector("figure") {
  if let parent = figure.parentNode,
     let i = parent.indexOfChild(figure) where i > 0,
     let p = parent.childAtIndex(i - 1) as? HTMLElement where p.tagName == "p"
  {
    print("we've got the paragraph! \(p)")
  } 
}
```
I'm just typing this in without trying it, so hopefully it almost compiles and sparks an idea for you.

There's also the CSS selector `figure + p` which would get you the `p` tags that come right after a `figure`.

**Comment by nolanw** [comment]
I'll assume the thumbs-up means you're all set, so I'ma close this issue. Please feel free to reopen or open a new issue as needed!
