### ISSUE TITLE
Parsing DOM

### ISSUE THREAD

**Issue by nishabe** [nolanw/HTMLReader#69]
Hi,
This is more of a question than an issue.
How do I use this library to search for a specific div and store the child element values to a model class instances?

As an example my HTML is a collection of divs as below.
```
<div class="rc">
<h3 class="r">
<a href="http://someurl">click here</a>
</h3>
</div>
```

Please help.

**Comment by nolanw** [comment]
Hello! You'll want to do something like this:

```swift
import Foundation

let markup: String = ...; // assume you've loaded this from somewhere
let document = HTMLDocument(string: markup)
var urls: [URL] = []
for link in document.nodes(matchingSelector: "a") {
  if let href = link.attributes["href"], let url = URL(string: href) {
    urls.append(url)
  }
}
```

You can find the elements you want using CSS selectors (above we just look for the elements named `<a>` but you can get much fancier if you need), and the elements you find have helpful properties like `attributes` and `textContent`.

Is that helpful?

**Comment by nishabe** [comment]
Thank you very much, Nolan. It really helped a lot. As you suggested, CSS selectors are used.
Adding my working ObjC code block below for the benefit of others:

`
// Parsing the response
    HTMLDocument *aDocument = [HTMLDocument documentWithString:string];
    NSArray *nodes = [aDocument nodesMatchingSelector:(@"h3[class^=\"r\"] > a")];
    if (nodes.count>0) {
        self.searchResults = [NSMutableArray array];
        for (HTMLElement *anElement in nodes) {
            if ([anElement objectForKeyedSubscript:@"href"]) {
                [self.searchResults addObject:[anElement objectForKeyedSubscript:@"href"]];
            }
        }
    }
`

**Comment by nolanw** [comment]
Happy to help! And thanks for posting your working code, too many people skip that step.
