### ISSUE TITLE
Broken pod

### ISSUE THREAD

**Issue by Dids** [nolanw/HTMLReader#70]
Since the headers are in the include/ folder, cocoapods/Xcode is unable to find them without adding include/ to pretty much all of the files.

**Comment by nolanw** [comment]
Hello! Can you share the error you're getting? What version of HTMLReader are you using?

Just now, I:

* Made a new Xcode project
* Did `pod init`
* Added `pod 'HTMLReader'`
* Did `pod install`

and everything seemed to be in order, with all the headers correctly appearing in the Pods project.

**Comment by Dids** [comment]
Added `pod 'HTMLReader'` and did `pod update`, which results in this:

```
/Path/Pods/HTMLReader/Sources/HTMLDocument.m:6:9: 'HTMLParser.h' file not found
```

I'll dig around, see if it's a project specific issue, or specific to the version of cocoapods(1.1.0.rc.2).

**Comment by nolanw** [comment]
Sounds good, thank you. And sorry for the inconvenience!

**Comment by Dids** [comment]
No worries, found the issue!

Specifically the filenames `HTMLParser.h/m` and `HTMLNode.h` were clashing with a different library I'm using, [BRYHTMLParser](https://github.com/irace/BRYHTMLParser). Neither library uses prefixed class names, so I guess it was only a matter of time. :P

**Comment by nolanw** [comment]
Ah, that's annoying.

(I cheekily wanted to claim HTML as a prefix. Not super surprised that failed.)

**Comment by Dids** [comment]
Added a quick PR to the other lib, using a fork of it for now. :)
