### ISSUE TITLE
Nullable to nonnull warning

### ISSUE THREAD

**Issue by guojiubo** [nolanw/HTMLReader#71]
I just clone the repo and try to build with Xcode 8(8A218a), it fails with an error `Implicit conversion from nullable pointer 'NSURL * _Nullable' to non-nullable pointer type 'NSURL * _Nonnull'`

```
// EncodingLabeler.m
static NSString * const EncodingLabelsURL = @"https://encoding.spec.whatwg.org/encodings.json";
NSData *data = [NSData dataWithContentsOfURL:[NSURL URLWithString:EncodingLabelsURL]];
```

I noticed there's a `CLANG_WARN_NULLABLE_TO_NONULL_CONVERSION` option set to YES in build settings. Since `[NSURL URLWithString:..]` returns a nullable result and `[NSData dataWithContentsOfURL:...]` expected a nonnull argument, it produces a warning. Also, due to the `Treat Warnings as Errors` is set to YES, the build fails.

I suppressed the warning by adding a temporary variable then the build passed.

```
static NSString * const EncodingLabelsURL = @"https://encoding.spec.whatwg.org/encodings.json";
NSURL *url = [NSURL URLWithString:EncodingLabelsURL];
NSData *data = [NSData dataWithContentsOfURL:url];
```

Hope it helps.

**Comment by nolanw** [comment]
Thanks! As you can probably guess, it's been some time since I ran the EncodingLabeler.

Out of curiosity, may I ask why you were building that target? It's not necessary to use HTMLReader. I hope it wasn't confusing!
