### ISSUE TITLE
Does not work with latest SPM

### ISSUE THREAD

**Issue by shvets** [nolanw/HTMLReader#73]
1. Requires to rename Tests into HTMLReaderTests

2. after renaming an regenerating project (swift package generate-xcodeproj) it returns error:

~//work/projects/swift/MyAPI/Packages/HTMLReader-2.0.1/Sources/HTMLNode.m:22:1: Cannot synthesize weak property in file using manual reference counting

when you open project in xcode.

**Comment by nolanw** [comment]
Hello! I haven't looked into this yet. But I plan to, and wanted to tell you that I'm not ignoring you!

**Comment by nolanw** [comment]
I've moved the tests folder so that part should be ok now.

As for the other problem, that should go away if you do `swift package generate-xcodeproj -Xcc -fobjc-arc`. I've updated the readme to make this more clear.

**Comment by nolanw** [comment]
@shvets I just pushed version 2.0.3 which seems to work nicely with the version of Swift Package Manager that comes with Xcode 8.2.1. Just make sure to pass those extra flags when you generate your Xcode project and you should be all set! Let me know if you run into any issues.
