### ISSUE TITLE
Can't upload to Itunes bacause of "No CFBundleVersion "

### ISSUE THREAD

**Issue by tqtifnypmb** [nolanw/HTMLReader#74]

**Comment by nolanw** [comment]
Hello! Can you provide any more information, like a screenshot or a copy of the error message you received? How did you add HTMLReader to your project – CocoaPods, Carthage, manually adding files? If you have your .ipa or .xcarchive, can you examine the contents for HTMLReader.framework and double-check that the Info.plist therein has a value for the key CFBundeVersion?

**Comment by tqtifnypmb** [comment]
Version: 2.0.3

<img width="489" alt="screen shot 2017-02-23 at 8 50 25 am" src="https://cloud.githubusercontent.com/assets/13230385/23239944/3a4611c8-f9a5-11e6-8bbc-5d7f6430911f.png">

**Comment by nolanw** [comment]
Yep, that's a missing CFBundleVersion! That "Build" field should not be empty.

You can do a quick fix by putting a number in there. I suggest the number `36`, but any number should do.

Can you share how you installed HTMLReader into your project? I'd like to avoid others having this issue in the future.

**Comment by tqtifnypmb** [comment]
I just fall back to 2.0.2. :p
I installed by Carthage

**Comment by emelyanova** [comment]
I've got the same issue also. Installed using Carthage also

**Comment by nolanw** [comment]
@tqtifnypmb @emelyanova I've spotted the problem! Please try version 2.0.5 which I've just pushed. Apologies for the inconvenience.

Alternately, if you would like a quick fix without updating versions:
* Locate HTMLReader's `Info.plist`.
* Find the line `<key>CFBundleVersion</key>`.
* The line immediately after should resemble `<integer>36</integer>`. Change it to `<string>36</string>`.
    * The number may not be 36 in your case. That's ok; it's the `integer` -> `string` change that's important.
