### ISSUE TITLE
Carthage Xcode 9 beta build fail

### ISSUE THREAD

**Issue by ilyakooo0** [nolanw/HTMLReader#79]
`Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project ~/Developer/carthageTest/Carthage/Checkouts/HTMLReader/HTMLReader.xcodeproj -scheme HTMLReader\ iOS -configuration Release -derivedDataPath ~/Library/Caches/org.carthage.CarthageKit/DerivedData/HTMLReader/v2.0.5 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/g5/0l8v577j5k976b1htv4rf5cc0000gn/T/carthage-xcodebuild.hK0Nzo.log`

**Comment by ilyakooo0** [comment]
Fixed by changing 
`github "nolanw/HTMLReader"`
to 
`github "nolanw/HTMLReader" "master"`

Must be a Carthage bug.

**Comment by nolanw** [comment]
I think it's because the fix is on master but I haven't tagged a version yet that includes it. By default Carthage grabs the highest version.
