### ISSUE TITLE
Xcode 9.3 build errors

### ISSUE THREAD

**Issue by agisboye** [nolanw/HTMLReader#82]
I'm getting a couple of build errors in Xcode 9.3, all related to string formatting in error messages, when building for ARM (Generic iOS Device). Xcode offers fix-its for all of them but I'm not sure it's the best solution. Would you care to take a look?

First error:
``
HTMLReader-master/Sources/HTMLSelector.m:30:32: Values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead
``

**Comment by agisboye** [comment]
Cheers!

**Comment by nolanw** [comment]
Thanks for the heads up! New version hading up to CocoaPods now.
