### ISSUE TITLE
values of type 'NSUInteger' should not be used as format arguments

### ISSUE THREAD

**Issue by de4me** [nolanw/HTMLReader#84]
HTMLSelector.m:30:32: error: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]

Carthage can't build submodule for ChatSecure application. Xcode 9.4 used.

**Comment by nolanw** [comment]
(Just in case anyone is confused: this warning is fixed in the latest version of HTMLReader, so I’m guessing OP updated their version and that solved the issue.)
