### ISSUE TITLE
Xcode 11 build errors

### ISSUE THREAD

**Issue by agisboye** [nolanw/HTMLReader#87]
When building with Xcode 11 (beta 2), there are three warnings about `long` being implicitly casted to `int`. Carthage treats these warnings as errors, meaning it won't build HTMLReader.

`
.../HTMLReader/Sources/HTMLEncoding.m:394:12: error: implicit conversion loses integer precision: 'NSComparisonResult' (aka 'enum NSComparisonResult') to 'int' [-Werror,-Wshorten-64-to-32]
`

I've worked around these issues by explicitly casting the result to an int:
[https://github.com/nolanw/HTMLReader/compare/master...agisboye:master](url)

I don't have much Objective-C experience, so I'm not sure if this is the preferred solution. If it is, let me know and I'll submit a PR.

**Comment by nolanw** [comment]
Hey! Thanks so much, that solution looks great. I cherry-picked it from your fork and just released version 2.1.4. Let me know if it works for you!

**Comment by agisboye** [comment]
It works great! However, I just noticed that 2.1.3 is still installed when using CocoaPods. Could you push the latest tag? Cheers!

**Comment by nolanw** [comment]
@agisboye Looks like CocoaPods knows what’s up: https://cocoapods.org/pods/HTMLReader says 2.1.4. Does `pod update HTMLReader` grab 2.1.4?

**Comment by agisboye** [comment]
I could've sworn it said 2.1.3 earlier. I just did a `pod update` and now it grabs 2.1.4. Huh. 🤷‍♂ Anyway, cheers!
