### ISSUE TITLE
Combining certain selectors doesn't work

### ISSUE THREAD

**Issue by Sweeper777** [nolanw/HTMLReader#88]
Selector of the form `x.y ~ z` doesn't seem to work. See this [fiddle](https://jsfiddle.net/w9k1ojnL/1/) for the correct behaviour. The code I used was:

```
let html = """
<div>
<span>1</span>
<span>2</span>
<span class="a">3</span>
<span>4</span>
<span>5</span>
<span>9</span>
</div>
"""
let document = HTMLDocument(string: html)
let nodes = document.nodes(matchingSelector: "span.a ~ span")
print(nodes.map { $0.textContent })
```

It prints "3", but I expect "4 5 9" just like in the fiddle.

**Comment by nolanw** [comment]
@Sweeper777 Yep, that was not at all working correctly. Thank you for reporting the issue! I've fixed it in HTMLReader 2.1.5 which I am releasing right now :)
