### ISSUE TITLE
How to save a web page as an html file, including pictures?

### ISSUE THREAD

**Issue by lzyroot** [nolanw/HTMLReader#90]
Hello nolanw.

How to save a web page as an html file

the html file contains all the content of the web page, including pictures

**Comment by nolanw** [comment]
Hello! HTMLReader can do some of the job, but unfortunately it doesn't offer a complete solution. I would say it depends on what you want to save. If it's just the HTML plus images in `<img>` elements, that's not so bad. But there are many, many ways an HTML document can pull in external resources (`<link>`, `<script>`, etc.) and a tool dedicated to preserving the document as a whole is a better bet than HTMLReader. Something like `wget`, with the `-p` and `-k` options, will do a better job.

If you're set on using HTMLReader, the general idea is to do what `wget`'s `-p` and `-k` options do. `-p` seeks out external resources and downloads them next to the HTML document, so you'd use HTMLReader to find all `<img>` elements and download the image from the src attribute (and then do the same for `<link>` (for CSS), `<script>` (for JavaScript), etc.). Then you'd do the equivalent of `wget -k`, where you edit those elements so they point to the new location of the external resources. HTMLReader can help with the editing part; for downloading things, URLSession should work.

Let me know if any of that is unclear! And if you try using HTMLReader for this and get stuck, I'm happy to help.

**Comment by lzyroot** [comment]
I want to use HTMLReader to save html files, which only contain the text and <img> elements in the webpage. I don’t see how to use it.

**Comment by nolanw** [comment]
Extending the example from the read me, you might try something like:

```swift
let document = HTMLDocument(string: """
    <p>
        Ahoy there, <b>sailor</b>!
    </p>
    """)
let destination = URL(fileURLWithPath: "some/path/my-file.html")
do {
  try document.serializedFragment.write(
    to: destination,
    atomically: true,
    encoding: .utf8
  )
} catch { print("could not save document: \(error)") }
```

The important part is getting the `serializedFragment` of the document, which is a string that you can save as you please.

My apologies for this not being more obvious!

**Comment by lzyroot** [comment]
Thanks

**Comment by nolanw** [comment]
I added an example to the read me, seemed like a good thing to include :)
