### ISSUE TITLE
Crash within runAdoptionAgencyAlgorithmForTagName

### ISSUE THREAD

**Issue by trix180** [nolanw/HTMLReader#95]
Hello,

I'd like to report an out of bound crash within `runAdoptionAgencyAlgorithmForTagName`. The crash is reproducible with the content of this URL http://thegreatstory.org/MD-writings.html or the HTML code below.

[thegreatstory.txt](https://github.com/nolanw/HTMLReader/files/9692069/thegreatstory.txt)

Best Regards.

**Comment by nolanw** [comment]
Thank you very much for the report! This is fixed in HTMLReader 2.2.1. I'll push the update to CocoaPods later today.

edit: 2.2.1 is now available via CocoaPods.
